---
title: Structure of Clinical Research
author: Alireza Behzadnia
date: '2018-03-26'
slug: research_design_intro
categories:
  - Clinical Research
  - Design
weight: 3
---

Clinical research is an essential part of practice of medicine. In short it is a project carried out by to investigate a research question - which should be focused on clinical aspect of medicine (i.e. the practice of medicine).

Structure of the research is heavily dependant on the subject of interest. However, almost all studies follow a logical and focused organisation. A study has to have:

  - **Research question(s)**

    - Which needs to be *FINER*: feasible, interesting, novel, ethical and relevant

  - **Background and significance**

    - Put the question in context and provides rationale for the study

  - **Design**

    - *Observation*
      - Cohort studies: participants are divided into groups and are studied over a specified time frame
        - Time frame: prospective or retrospective
      - Cross sectional study
      - Case control study

    - *Experimental*
      - Clinical trials
        - Randomised blinded trial

  - **Subjects**

    - The population of interest
    - Requires inclusion and exclusion criteria to define the population of interest
    - Sampling: How the population will be sampled and how the participants would be recruited

  - **Variables**

    - Response variable(s): what will be studied - or more commonly - measured?
      - Also known as: outcome variable or dependent variable
      - Plotted on the Y-axis
    - Explanatory variable(s): what will be controled? the treatment
      - Also known as: predictor variable or independent variable
      - Plotted on the X-axis
    - Confounding variable(s): variables that may influence our measured outcomes.
      - This should always be factored in the study design.
      - Randomization is a common method of minimizing the influence of confounding variables.

  - **Statistics**

    - The most important and crucial part of the study
    - How will we go about answering our question?
    - Involves:
      - Hypothesis
      - Estimate of the required sample size (power of the study)
      - Statistical method that will assess the hypothesis
